### ISSUE TITLE
go get doesn't work and neither does building

### ISSUE THREAD

**Issue by Elsie19** [5nord/shini#1]
running `go get -u github.com/5nord/shini` waits for a second, exits with code 0, but doesn't run. Cloning then running `go build` shows this:

`config.go:4:2: cannot find package "github.com/pelletier/go-toml" in any of:
	/usr/lib/go-1.13/src/github.com/pelletier/go-toml (from $GOROOT)
	/root/go/src/github.com/pelletier/go-toml (from $GOPATH)
config.go:5:2: cannot find package "github.com/pelletier/go-toml/query" in any of:
	/usr/lib/go-1.13/src/github.com/pelletier/go-toml/query (from $GOROOT)
	/root/go/src/github.com/pelletier/go-toml/query (from $GOPATH)`

**Comment by 5nord** [comment]
I am not sure why you have this error. It could be related to missing support for modules in shini. I created a shini-module and updated install instructions. Would you mind trying it out?

**Comment by Elsie19** [comment]
It creates a folder called go. I navigated /tmp/go/bin. There is a binary called shini. I had to move it to /bin and it worked

**Comment by 5nord** [comment]
This still feels a little off. I would have expected the binary to be installed to `/root/go/bin`, and not to `/tmp/go/bin`. I don't think this issue is related to shini, though; but rather to your Go setup, maybe? I am no Go-packaging expert, but could you check the go environment (`go env`) and go version? Maybe this sheds some light on the issue.

**Comment by Elsie19** [comment]
I’m not in front of my computer now, but I had a thought. Maybe `/root/go/bin` in my `$PATH`. I’ll check and see tonight if it installed it to `/root/go/bin` and made a duplicate in `/tmp`.

**Comment by Elsie19** [comment]
```bash
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/henry/.cache/go-build"
GOENV="/home/henry/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/henry/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/henry/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build919171645=/tmp/go-build -gno-record-gcc-switches"```
